--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/Tebex
build-by-default: true
branches:
  - pmmp-api5
  - pmmp-api4
  - master
projects:
  Tebex:
    path: ""
    libs:
      - src: muqsit/tebexapi/TebexApi
        version: ^0.2.1
...
